name: flutter_remote_value
description: Package that provide widget which map remote value to widgets
version: 0.0.4+1
homepage: https://github.com/massa-org/massa.flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^7.1.0
  freezed_annotation: ^0.14.2
  remote_value: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  build_runner: ^2.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
