name: blop
description: A new Flutter package project.
version: 0.0.2
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  # without this test blop_test.dart:133 go to segfault
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^0.14.2

  bloc: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.3

  freezed: ^0.14.2
  rxdart: ^0.27.1 #for testing
  pedantic: ^1.11.1


flutter:
