name: massa_utils
description: Utilities to work with bloc
version: 0.0.2
homepage: https://github.com/massa-org/bloc_extension


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  
dev_dependencies:
  pedantic: ^1.11.1
