name: massa_utils
description: Utilities to work with bloc
version: 0.1.0
homepage: https://github.com/massa-org/massa.flutter


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^8.0.0
  
dev_dependencies:
  pedantic: ^1.11.1
