targets:
  $default:
    builders:
      generators|annotations:
        enabled: true

builders:
  generators:
    target: ":generators"
    import: "package:blop_generator/blop_generator.dart"
    builder_factories: ["generateBlop"]
    build_extensions: { ".dart": [".blop_generator.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
