name: blop_generator
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  blop: 
    git: 
      url: git@github.com:massa-org/bloc_extension.git
      path: blop

  build: ^2.0.0
  source_gen: ^1.0.3
  analyzer: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  # pedantic: 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  