name: blop_generator
description: Package to generate blop method call boilerplate code
version: 0.1.0
homepage: https://github.com/massa-org/massa.flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  blop: ^0.1.0

  build: ^2.0.0
  source_gen: ^1.0.0
  analyzer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  pedantic: ^1.11.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
# flutter:

  