name: remote_value
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  bloc:
  blop: 
    git: 
      url: git@github.com:massa-org/bloc_extension.git
      path: blop
  massa_utils:
    path: ../massa_utils
    # git: 
      # url: git@github.com:massa-org/bloc_extension.git

  # for persistent store
  hive: ^2.0.0
  freezed_annotation: ^0.14.2
  
  # hive_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: 

  blop_generator: 
    git: 
      url: git@github.com:massa-org/bloc_extension.git
      path: blop_generator
  freezed: ^0.14.2
  
  
  build_runner: ^2.0.0