name: example
description: A new Flutter package project.
version: 0.1.0
homepage:

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  bloc: ^8.0.0
  blop: ^0.1.0

  freezed_annotation: ^1.0.0
  massa_utils: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.0.3

  freezed: ^1.0.0
  blop_generator: 
    path: ../

  
flutter: