name: example
description: A new Flutter package project.
version: 0.0.2
homepage:

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  bloc: ^7.0.0
  blop: ^0.0.2

  freezed_annotation: ^0.14.2
  massa_utils: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.0.3

  freezed: ^0.14.2
  blop_generator: 
    path: ../

  
flutter: